version: '3'

services:
  backtesting:
    build: .
    volumes:
      - ./data:/usr/src/app/data
    ports:
      - "8000:8000"

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    volumes:
      - .:/usr/src/app
    ports:
      - "8501:8501"
